### ISSUE TITLE
Cursor not shown back after run

### ISSUE THREAD

**Issue by SBoudrias** [sindresorhus/log-update#1]
When done is called, it doesn't show the cursor back.

**Comment by sindresorhus** [comment]
Hmm, it should. I'm using [`restore-cursor`](https://github.com/sindresorhus/restore-cursor/blob/master/index.js) to restore it on exit. How are you exiting? Maybe a way [`exit-hook`](https://github.com/sindresorhus/exit-hook/blob/master/index.js) doesn't catch.

**Comment by SBoudrias** [comment]
Ah, that wasn't very explicit as it's hidden into the cli-cursor module. Looks like it's working fine :)
