### ISSUE TITLE
Calling log-update breaks SIGINT signal handlers

### ISSUE THREAD

**Issue by laurynasl-wix** [sindresorhus/log-update#17]
It seems that using this library breaks the expected behaviour of SIGINT listeners. If logUpdate is used before registering a SIGINT listener, the listener is not called at all and the process exits immediately, if logUpdate is first called after registering a listener, the listener is called, but the process still exits. If logUpdate is not called, the code below doesn't exit of first SIGINT, but does so on the second one (which is the expected behaviour) 

```js
const logUpdate = require('log-update')

//logUpdate('This makes my SIGINT listener not called at all, and the process immediately exits')

process.stdin.on('data', () => {
	// just so we don't exit
})

let count = 0
process.on('SIGINT', () => {
	if (count >= 1) {
		process.exit(0)
	}
	console.log('press CTRL+C again to exit')
	count ++ 
})

//logUpdate('this makes my SIGINT listener be called, but the process still exits')
```

Uncommenting only the first usage yields 
```
~/IdeaProjects/temp$ node index.js
This makes my SIGINT handler not called at all, and the process immediately exits
^C~/IdeaProjects/temp$
```

Uncommenting only the second usage yields 
```
~/IdeaProjects/temp$ node index.js
this makes my SIGINT handler be called, but the process still exits
^Cpress CTRL+C again to exit
~/IdeaProjects/temp$
```

Uncommenting both yields 
```
~/IdeaProjects/temp$ node index.js
^Cpress CTRL+C again to exit
^C~/IdeaProjects/temp$
```

Tested on node v6.10.1 and v7.7.4, macOS 10.12.3 (16D32)

**Comment by laurynasl-wix** [comment]
Any ETA on when this will be released?

**Comment by ivan-kleshnin** [comment]
For some reason `logUpdate` blocks `SIGINT` if at least one timer (`setInterval / setTimeout`) is running:

```js
import logUpdate from "log-update"

logUpdate("test")
setInterval(() => console.log(new Date()), 1000)
// Try to Ctrl-C...
```

A workaround is to manually clear an interval.

```js
process.on("SIGINT", () => {
  clearInterval(interval)
  logUpdate.done()  
})
```

Still I'm curios why it happens... if someone knows – please share 🙏
