### ISSUE TITLE
Long lines are not taken into account

### ISSUE THREAD

**Issue by Jameskmonger** [sindresorhus/log-update#19]
Long lines are not wrapped correctly.

This is because in `render` by the time the output is split `out.split('\n')` they are not always newlines, so their length is not taken into account.

Here is an example where the issue occurs:

```
"use strict";

const logUpdate = require("log-update");

let first = "Itwasgettingdark,andweweren’tthereyet.Italyismyfavoritecountry;infact,Iplantospendtwoweekstherenextyear.Catsaregoodpets,fortheyarecleanandarenotnoisy.Wheredorandomthoughtscomefrom?Christmasiscoming.";
let second = "Theriverstolethegods.Weneedtorentaroomforourparty.Thelakeisalongwayfromhere.Isitfree?WehaveneverbeentoAsia,norhavewevisitedAfrica.";
let third = "Maryplaysthepiano.Theshootersaysgoodbyetohislove.Thelakeisalongwayfromhere.Shouldwestartclassnow,orshouldwewaitforeveryonetogethere?WehavealotofraininJune.";

logUpdate(first);
setTimeout(() => logUpdate(second), 1000);
setTimeout(() => logUpdate(third), 2000);
```

![cmder windows 10](http://i.imgur.com/TKXhGan.png)

It can be fixed by going through all lines and seeing which are longer than the console, like so:

```
let lines = out.split('\n');
prevLineCount = lines.length;

lines.forEach(l => {
	prevLineCount += Math.floor(l.length, termSize().columns);
});
```

**Comment by Jameskmonger** [comment]
@SamVerschueren #12 did not fix this so I have logged as a more specific issue

**Comment by SamVerschueren** [comment]
You are using Windows right?

**Comment by Jameskmonger** [comment]
Yes I am, Windows 10

**Comment by Jameskmonger** [comment]
I feel that this could be an issue with `wrap-ansi` instead @SamVerschueren

**Comment by SamVerschueren** [comment]
Yes I was thinking the same. Because currently, the lines are wrapped and `\n` is inserted at the end of the lines. So in the end, we should have the same result as your workaround. Could you create a minimal test to see if `wrap-ansi` fails on Windows?

**Comment by Jameskmonger** [comment]
@SamVerschueren D'oh!

From the `wrap-ansi` docs:

> ##### hard
> 
> Type: `boolean`<br>
> Default: `false`
> 
> By default the wrap is soft, meaning long words may extend past the column width. Setting this to `true` will make it hard wrap at the column width.

For a full fix, we need to make two changes:

- Set `width` to `process.stdout.columns - 1` (otherwise there is a single blank line added)
- Add `hard: true` to `wrapAnsi` options.

I'll put a PR in.
