### ISSUE TITLE
Unexpected control characters when require’d and not invoked

### ISSUE THREAD

**Issue by wooorm** [sindresorhus/log-update#2]
I came across this issue when building watch functionality using the excellent elegant spinner, and it was hard to track down!

Some background: you can run `mdast` either with or without `--watch`. When not watching, nothing is written to stdout(4) normally. If you want, you can output a file to stdout(4) though.

My mother taught me to always write unit-tests, so I did: testing stdout(4) on some sample fixture to be an empty string.

Astonishment, I was, when I came to the conclusion that the tests started failing after including `log-update` (and not using it). I tracked it down to [probably this](https://github.com/sindresorhus/restore-cursor/blob/master/index.js#L6). I’m not sure exactly where it originates though (maybe useful: Bash reported stdout(4)’’s length to be 18 characters).

Back to some actionable points: I worked around this by lazy-loading `log-update`, but maybe other people will also come across this too. Is it a bug? Interested in fixing it?

:+1:

**Comment by chcokr** [comment]
@sindresorhus When will you release a12769f ?

**Comment by sindresorhus** [comment]
When it's confirmed it's a suitable fix for `mdast`.

**Comment by chcokr** [comment]
cc wooorm/mdast#57

**Comment by wooorm** [comment]
@sindresorhus sindresorhus/log-update#3 together with sindresorhus/cli-cursor#2 resolve this issue. in mdast’s code-base.
