### ISSUE TITLE
Appending new multiline messages causes weird display issues

### ISSUE THREAD

**Issue by mAAdhaTTah** [sindresorhus/log-update#28]
Reproducible code:

```js
const logUpdate = require('log-update');

const log = logUpdate.create(process.stdout);
const messages = [];

const interval = setInterval(() => {
    log(messages.join('\n'));

    if (messages.length > 10) {
        clearInterval(interval);
    }

    messages.push(`This is a new multiline message.

Time is now: ${Date.now()}`)
}, 20);
```

Result:

<img width="149" alt="bash_" src="https://user-images.githubusercontent.com/4371429/34381756-8afed648-ead8-11e7-9e4f-097103429498.png">

This occurs on iTerm2 v3.1.2, using the hotkey visor (if that's relevant). The test case above is only reproducible when I've split-screened the window (either horizontally or vertically). However, the original issue I'm experiencing in ink (https://github.com/vadimdemedes/ink/issues/48) occurs regardless of whether the window is split-screened.

This is kind of a corner-y case, but happy to help investigate.

**Comment by mAAdhaTTah** [comment]
Couple of things to note here after more digging:

1. The writes have to occur fast enough & with a large enough replacement string to cause the issue. What these numbers are appear to be dependent upon the size of the terminal window.
2. Setting stdout to blocking (via `process.stdout._handle.setBlocking(true);`) doesn't resolve the issue.
3. This was reproducible on Node 6, 8, and latest.

**Comment by sindresorhus** [comment]
There has been a lot of improvements since this issue was opened. I cannot reproduce this with the latest `log-update` (v4), latest iTerm, and Node.js 10.18 and 12.13:

<img width="319" alt="Screenshot 2020-02-20 at 15 10 05" src="https://user-images.githubusercontent.com/170270/74913383-14d6c800-53f3-11ea-90d1-c86507dc399b.png">

Would you be able to try again?

**Comment by mAAdhaTTah** [comment]
Tested latest log-update version w/ the reproducible code sample on Node 10, 12 & latest. Problems seems to be resolved. Thanks for your help!
