### ISSUE TITLE
Strange behavior when resizing terminal window

### ISSUE THREAD

**Issue by belemaire** [sindresorhus/log-update#36]
I am noticing a strange behavior when shrinking my terminal window so that it masks previously logged text and then making it bigger again. The gif below expose the problem :

![issuelogupdate](https://user-images.githubusercontent.com/1390588/43414696-646c7850-93e8-11e8-8538-b442fe0a8234.gif)

The code is very minimal, it just log a new line every second. 

```js
const logUpdate = require('log-update')
let str = ''
let idx = 0
setInterval(() => {
  str += `Hello ${idx++}\n`
  logUpdate(str)
}, 1000)
```

My workstation is running maxOS High Sierra (v10.13.5) / Node v8.11.3. 
I am using `iTerm2` with `zsh` so at first I thought it might come from some setting of those, but I tried with default Terminal with bash (as captured in the gif) and problem is the same.

Any idea what could cause this glitch ?

**Comment by vadimdemedes** [comment]
Problem here is that terminals don't support clearing lines outside of your "viewport". So if you have output with 5 lines, but terminal height is 4 lines, you can't erase the first line.

**Comment by belemaire** [comment]
@vadimdemedes 
Thanks for the details :+1:
Not much that can be done about it I'd assume, so closing this issue.
