### ISSUE TITLE
Incorrect windows handling of line wraps

### ISSUE THREAD

**Issue by herecydev** [sindresorhus/log-update#41]
In [this line of code](https://github.com/sindresorhus/log-update/blob/master/index.js#L15) you are clearly trying to cater for some specific windows issue. However this is not the case:

![image](https://user-images.githubusercontent.com/11328618/62075193-65f75280-b23c-11e9-9120-b9bb4e6598a4.png)

Causes:

![image](https://user-images.githubusercontent.com/11328618/62075218-74de0500-b23c-11e9-85de-b9a5f162de52.png)

Hopefully you can see the premature line wrap that's occurring.

Can you please rethink why [the addition was made here](https://github.com/sindresorhus/log-update/issues/19). I have seen on 4 different windows machines the same *incorrect* behavior.

**Comment by sindresorhus** [comment]
> Can you please rethink why the addition was made here.

You can do that too. "git blame" it.

**Comment by herecydev** [comment]
I linked the thread where the change was originally discussed, and [the PR is here](https://github.com/sindresorhus/log-update/pull/21). What I'm trying to get across is that this doesn't appear to be correct anymore.

**Comment by sindresorhus** [comment]
Just because you cannot reproduce doesn’t mean it’s not a problem anymore. I think some more investigation is needed.

**Comment by herecydev** [comment]
Not for a second claiming it's the one true solution for all windows versions. But I have done as much due dilligence by trying on several machines with different windows versions. What further steps can I help with so we can progress?

**Comment by herecydev** [comment]
I've tried to recreate the original issue on the following node versions:

4.9.1
6.17.1
8.16.0
10.16.12
12.6.0

on Windows 10 (release: 1903)

And all of them exhibit the correct behavior with the windows specific logic removed. Can @Jameskmonger shed any further light on the original issue & versions to recreate?

**Comment by Jameskmonger** [comment]
@herecydev This is the original issue:

https://github.com/sindresorhus/log-update/pull/21#issuecomment-317734339

I will try to reproduce this on Windows 10 v1903 later

**Comment by Jameskmonger** [comment]
I don't have v1903, but I'm on v1803 and can see that after deleting the windows-specific code the issue doesn't present itself anymore.

**Comment by herecydev** [comment]
Thanks for the info! I found the original issue but had no idea what version of Windows you were using at the time that exhibited the problem. Is it possible it was < Windows 10?

**Comment by Jameskmonger** [comment]
@herecydev It was definitely Windows 10 that had the issue, but obviously a version from 2 years ago.

**Comment by herecydev** [comment]
@Jameskmonger Thanks very much! @sindresorhus is this enough info to make something actionable?

**Comment by Jameskmonger** [comment]
@herecydev If removing the Windows-specific code fixes your issue, and it doesn't reintroduce my old issue on relatively-recent versions of Windows, I think a PR just removing that windows-specific code will work
